# Generated by Django 3.2 on 2021-04-22 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizza',
            name='extra_topping',
        ),
        migrations.AddField(
            model_name='pizza',
            name='extra',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
