# Generated by Django 3.2.2 on 2021-05-07 09:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0002_auto_20210422_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='ordered',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
